In [2]:
import numpy as np
arr_1d=np.array([1,2,3,4,5])
print("1D_Array:",arr_1d)
print("Multipliacation of 1D_Array:",arr_1d*2)
print("Addition of 1D_Array:",arr_1d+2)

import time
start = time.time()
py_list = [i*2 for i in range(1,1000000)]
end = time.time()
print("Execution Time:", end - start)
start =time.time()
np_array = np.arange(1000000)*2
end=time.time()
print("executuon time:",end-start)


1D_Array: [1 2 3 4 5]
Multipliacation of 1D_Array: [ 2  4  6  8 10]
Addition of 1D_Array: [3 4 5 6 7]
Execution Time: 0.057103633880615234
executuon time: 0.005868673324584961


# Creating Array From Scratch


In [4]:
zeros = np.zeros((3,3))
print("Zeros:",zeros)

ones = np.ones((3,3))
print("Ones:",ones)

full = np.full((3,3),5)
print("Full:",full)

random = np.random.random((3,3))
print("Random:",random)

Sequence = np.arange(0,11,2)
print("Sequence:",Sequence)


Zeros: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Full: [[5 5 5]
 [5 5 5]
 [5 5 5]]
Random: [[0.36703483 0.11876286 0.20129752]
 [0.25106417 0.01164539 0.52464829]
 [0.94837269 0.18918438 0.11416994]]
Sequence: [ 0  2  4  6  8 10]


# Vector Matrix & Tensor

In [5]:
vector = np.array([1,2,3])
print("Vector:",vector)

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix:",matrix)

tensor = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
print("Tensor:",tensor)



Vector: [1 2 3]
Matrix: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tensor: [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


### Array Properties


In [7]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array:",arr)
print("Shape:",arr.shape)
print("Size:",arr.size)
print("Dimension:",arr.ndim)
print("Data Type:",arr.dtype)
print("Item Size:",arr.itemsize)

Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Size: 9
Dimension: 2
Data Type: int64
Item Size: 8


### Array Reshaping

In [10]:
arr = np.arange(12)
print("Array:",arr)

reshaped = arr.reshape((3,4))
print("Reshaped:",reshaped)

flattened = reshaped.flatten()
print("Flattened:",flattened)

#Returs View instead of copy
raveled = reshaped.ravel()
print("Raveled:",raveled)

#Transpose
transposed = reshaped.T
print("Transposed:",transposed)

Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
