### Numpy Array Operations


In [2]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Basic Slicing", arr[1:5])
print("Basic Slicing", arr[4:])
print("Basic Slicing", arr[:4])
print("Basic Slicing", arr[::2])
print("Basic Slicing", arr[1:5:2])
print("Basic Slicing", arr[-3:-1])
print("Basic Slicing", arr[-3:])

Basic Slicing [2 3 4 5]
Basic Slicing [5 6 7 8 9]
Basic Slicing [1 2 3 4]
Basic Slicing [1 3 5 7 9]
Basic Slicing [2 4]
Basic Slicing [7 8]
Basic Slicing [7 8 9]


In [5]:

arr_2d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])  # 2D array
print("2D Array Slicing", arr_2d[0, 1:4])
print("Entire Row", arr_2d[1])
print("Entire Column", arr_2d[:, 2])
print("Entire Row", arr_2d[1, :])

2D Array Slicing [2 3 4]
Entire Row [ 6  7  8  9 10]
Entire Column [3 8]
Entire Row [ 6  7  8  9 10]


### Sorting

In [4]:
unsorted_arr = np.array([3, 2, 0, 1, 5, 4, 6, 7, 8])
arr = np.sort(unsorted_arr)
print("Sorted Array", arr)

unsorted_2d_arr = np.array([[3, 2, 0, 11, 5], [4, 6, 7, 8, 9]])
arr = np.sort(unsorted_2d_arr, axis=0)
print("Sorted 2D Array Column", arr)

Sorted Array [0 1 2 3 4 5 6 7 8]
Sorted 2D Array Column [[ 3  2  0  8  5]
 [ 4  6  7 11  9]]


### Filtering

In [7]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9,10])
evennumbers = numbers[numbers % 2 == 0]
print("Even Numbers", evennumbers)



Even Numbers [ 2  4  6  8 10]


### Filter With Mask

In [8]:
mask = numbers > 5
print("Numbers greater than 5", numbers[mask])

Numbers greater than 5 [ 6  7  8  9 10]


### Fancy Indexing V/S np.where()

In [9]:
where_indices = np.where(numbers > 5,numbers*2,numbers)
print("Indices of numbers greater than 5", where_indices)

indices = [0,2,4]
print("Elements at indices", numbers[indices])



Indices of numbers greater than 5 [ 1  2  3  4  5 12 14 16 18 20]
Elements at indices [1 3 5]


### Adding and Removing 

In [10]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1,arr2))
print("Concatenated Array", arr)


Concatenated Array [1 2 3 4 5 6]


### Array Compatibility

In [11]:
a = np.array([1, 2,3])
b = np.array([4, 5, 6,7])
c= np.array([7, 8, 9])
print("Compatibilty Check", a.shape == b.shape)
print("Compatibilty Check", a.shape == c.shape)


Compatibilty Check False
Compatibilty Check True


In [12]:
original_arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
new_row = np.array([9,10, 11, 12])
with_new_row = np.vstack((original_arr, new_row))
print("New Row Added", with_new_row)

new_col = np.array([[13], [14]])
with_new_col = np.hstack((original_arr, new_col))
print("New Column Added", with_new_col)


New Row Added [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
New Column Added [[ 1  2  3  4 13]
 [ 5  6  7  8 14]]


In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
delete_arr = np.delete(arr, 1)
print(" Array  after Deletation", delete_arr)

 Array  after Deletation [1 3 4 5 6 7 8 9]


In [ ]:
help(np.vstack)

Help on _ArrayFunctionDispatcher in module numpy:

vstack(tup, *, dtype=None, casting='same_kind')
    Stack arrays in sequence vertically (row wise).

    This is equivalent to concatenation along the first axis after 1-D arrays
    of shape `(N,)` have been reshaped to `(1,N)`. Rebuilds arrays divided by
    `vsplit`.

    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.

    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the first axis.
        1-D arrays must have the same length. In the case of a single
        array_like input, it will be treated as a sequence of arrays; i.e.,
        each element along the zeroth axis is treated as a separate array.

    dtype : str 

In [16]:
help(np.genfromtxt)

Help on function genfromtxt in module numpy:

genfromtxt(
    fname,
    dtype=<class 'float'>,
    comments='#',
    delimiter=None,
    skip_header=0,
    skip_footer=0,
    converters=None,
    missing_values=None,
    filling_values=None,
    usecols=None,
    names=None,
    excludelist=None,
    deletechars=" !#$%&'()*+,-./:;<=>?@[\\]^{|}~",
    replace_space='_',
    autostrip=False,
    case_sensitive=True,
    defaultfmt='f%i',
    unpack=None,
    usemask=False,
    loose=True,
    invalid_raise=True,
    max_rows=None,
    encoding=None,
    *,
    ndmin=0,
    like=None
)
    Load data from a text file, with missing values handled as specified.

    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.

    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension