# Program to demostrate the slice operation used to access the elements of the list


In [7]:
num_list=[1,2,3,4,5,6,7,8,9,10]
print("Num list is ",num_list)

Num list is  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [11]:
print("First Element in the List   ",num_list[0])
print("num list[2:5]",num_list[2:5])
print("Num_list[::2]=",num_list[::2])
print("Num_list[1::2]=",num_list[1::3])

First Element in the List    1
num list[2:5] [3, 4, 5]
Num_list[::2]= [1, 3, 5, 7, 9]
Num_list[1::2]= [2, 5, 8]


 # Program to illustrate update value in a list

In [16]:
num_list=[1,2,3,4,5,6,7,8,9,10]
print(" list is ",num_list)
num_list[5] =100
print("List after update is ",num_list)
num_list.append(200)
print("Num list is ",num_list)
del num_list[3]
print("List after deleting a value is ",num_list)
del num_list[2:5]  # delete list value for index 2 to 4 not include 5 index value
print("List after deleting a value is ",num_list)


 list is  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
List after update is  [1, 2, 3, 4, 5, 100, 7, 8, 9, 10]
Num list is  [1, 2, 3, 4, 5, 100, 7, 8, 9, 10, 200]
List after deleting a value is  [1, 2, 3, 5, 100, 7, 8, 9, 10, 200]
List after deleting a value is  [1, 2, 7, 8, 9, 10, 200]


# Program illustrate nested list


In [10]:
list1=[[[1,3,4,5],[1,2]],[[3,4,5,6],[2,3,5,6]]]
list1.append([[(1,3),(3,5),(7,8)],[4,5]])
i=0
while i<len(list1):
    print("List1[",i,"]=",list1[i])
    i+=1
print(len(list1[2][0]))

List1[ 0 ]= [[1, 3, 4, 5], [1, 2]]
List1[ 1 ]= [[3, 4, 5, 6], [2, 3, 5, 6]]
List1[ 2 ]= [[(1, 3), (3, 5), (7, 8)], [4, 5]]
3


 # Program to  create a copy as well as the clone of the original list

In [22]:
list1=[1,2,3,4,5,6,7]
list2 = list1
print("List1 ",list1)
print("List2",list2)
list3 = list1[2:5]
print("List3",list3)


List1  [1, 2, 3, 4, 5, 6, 7]
List2 [1, 2, 3, 4, 5, 6, 7]
List3 [3, 4, 5]


# Program to show the sort() list element

In [2]:
list1 =['1','a','abc','2','B','def']
list1.sort() # sort() method  used ASCII value to sort the values in the list
print(list1)

['1', '2', 'B', 'a', 'abc', 'def']


# Program to illustrate operation on a stack(using list as stack)


In [39]:
stack=[100,200,300,400,500,600]
print("Original Stack is :",stack)
stack.append(700)
print("Stack after push element in  Stack is :",stack)
stack.pop()
print("Stack after pop element in  Stack is :",stack)
last_element_index = len(stack)-1
print("Value obtained after peep operation is :",)
stack[last_element_index]


#Note :The del statement and the pop() method does the same thing. difference between them is that pop()
#return the removed item


Original Stack is : [100, 200, 300, 400, 500, 600]
Stack after push element in  Stack is : [100, 200, 300, 400, 500, 600, 700]
Stack after pop element in  Stack is : [100, 200, 300, 400, 500, 600]
Value obtained after peep operation is :


600

# Program to show the implementation of a queue using list data structure

queue=[1,2,3,4,5,6]
print("Original Queue is ",queue)
queue.append(7)
print("Queue after insertion is",queue)
queue.pop(0)
print("Queue after delete is :",queue)
print("Value  obtained after peep operation is",queue[(len(queue)-1)])

# Program  to combine three lines of code into one(List Compression)
# list =[expression for varible in sequence]

In [43]:
cube=[i**3 for i in range(11)]
print(cube)

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]


# Program to combine and print elements of two list using list comprehension

In [44]:
print([(x,y) for x in [10,20,30] for y in [30,10,40] if x!=y] )

[(10, 30), (10, 40), (20, 30), (20, 10), (20, 40), (30, 10), (30, 40)]


In [12]:
from array import array
listA = list(range(0,5))
for item in listA:
    print(item)
arrayA = array("i", listA)
for item in arrayA:
    print(item)

0
1
2
3
4
0
1
2
3
4


In [30]:
import numpy as np
l=[[[ 0.44468541, -0.80929881,  0.09252818,  0.61949924,  0.93312086,
         0.66265084, -0.06055091,  0.10337879, -0.28301609,  0.78255347]],
       [[ 0.40173856, -1.47123106,  0.78252329,  1.09096851,  0.29170062,
         1.20907384,  0.59024852,  1.93484774,  1.09650167, -0.06866256]]]
print(l)

[[[0.44468541, -0.80929881, 0.09252818, 0.61949924, 0.93312086, 0.66265084, -0.06055091, 0.10337879, -0.28301609, 0.78255347]], [[0.40173856, -1.47123106, 0.78252329, 1.09096851, 0.29170062, 1.20907384, 0.59024852, 1.93484774, 1.09650167, -0.06866256]]]


In [31]:
ll= np.asarray(l)
print(ll)
print(ll.shape)

[[[ 0.44468541 -0.80929881  0.09252818  0.61949924  0.93312086  0.66265084
   -0.06055091  0.10337879 -0.28301609  0.78255347]]

 [[ 0.40173856 -1.47123106  0.78252329  1.09096851  0.29170062  1.20907384
    0.59024852  1.93484774  1.09650167 -0.06866256]]]
(2, 1, 10)


In [29]:
lz = np.zeros((3,3,3))
print(lz)

[[[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]]


In [38]:
for i in  range(9,8,-1):
    print(i)

9


In [33]:
print(l)

range(10, 1, -1)


In [39]:
a=[[1,2,3],[4,5,6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [40]:
print(np.mean(a))

3.5
